#ifndef _AMBXLIGHT_IOCTL_H__
#define _AMBXLIGHT_IOCTL_H__

#include <linux/ioctl.h>

#define AMBXLIGHT_IOCTL_MAGIC  0xAB

/* define ioctl option */
#define AMBXLIGHT_IOCTL_TELL   _IOC( _IOC_NONE,  AMBXLIGHT_IOCTL_MAGIC, 0x00, 0)
#define AMBXLIGHT_IOCTL_SET    _IOC( _IOC_WRITE, AMBXLIGHT_IOCTL_MAGIC, 0x01, sizeof(char))
#define AMBXLIGHT_IOCTL_QUERY  _IOC( _IOC_NONE,  AMBXLIGHT_IOCTL_MAGIC, 0x02, 0) 
#define AMBXLIGHT_IOCTL_GET    _IOC( _IOC_READ,  AMBXLIGHT_IOCTL_MAGIC, 0x03, sizeof(char))
#define AMBXLIGHT_IOCTL_RESET  _IOC( _IOC_NONE,  AMBXLIGHT_IOCTL_MAGIC, 0x04, 0)

/* Define transfer mode */
#define AMBXLIGHT_MODE_RAW	0x01
#define AMBXLIGHT_MODE_COLOR	0x02
#define AMBXLIGHT_MODE_HEXSTRING	0x04


#endif
